stages:
  - deploy-iis
  - deploy-apache

IIS Deployment:
  stage: deploy-iis
  script:
    - powershell .\deploy.ps1
  tags:
    - iis

Apache Deployment:
  stage: deploy-apache
  script:
    - mkdir /var/www/html/enpaul.new
    - rm ./deploy.ps1
    - rm ./web.config
    - rm ./.gitlab-ci.yml
    - cp -r ./* /var/www/html/enpaul.new/
    - cp ./.htaccess /var/www/html/enpaul.new/
    - mv /var/www/html/enpaul /var/www/html/enpaul.old
    - mv /var/www/html/enpaul.new /var/www/html/enpaul
    - rm -r /var/www/html/enpaul.old
  tags:
    - apache
