sync_website:
  script:
    - New-Item -Path "C:\inetpub\wwwroot\" -Name enpaul.new -ItemType Directory -Force
    - Copy-Item -Path .\* -Destination "C:\inetpub\wwwroot\enpaul.new\" -Force -Recurse
    - Rename-Item -path .\CKCADTech -NewName CKCAD -Force
    - Remove-Item -path "C:\inetpub\wwwroot\enpaul.net\*" -Recurse -Force
  tags:
    - null
