stages:
  - deploy-release-apache
  - deploy-dev-apache
  - deploy-release-iis
  - deploy-dev-iis

IIS Production:
  stage: deploy-release-iis
  script:
    - powershell .\.ci-release.ps1
  only:
    - master
  tags:
    - release-iis

IIS Development:
  stage: deploy-dev-iis
  script:
    - powershell .\.ci-dev.ps1
  only:
    - development
  tags:
    - dev-iis

Apache Production:
  stage: deploy-release-apache
  script:
    - "[ -d /var/www/html/build-tmp.enpaul ] && rm -r /var/www/html/build-tmp.enpaul"
    - mkdir /var/www/html/build-tmp.enpaul
    - cp -r ./* /var/www/html/build-tmp.enpaul/
    - rm /var/www/html/build-tmp.enpaul/web.config
    - "[ -d /var/www/html/enpaul ] && mv /var/www/html/enpaul /var/www/html/enpaul.old"
    - mv /var/www/html/build-tmp.enpaul /var/www/html/enpaul
    - "[ -d /var/www/html/enpaul.old ] && rm -r /var/www/html/enpaul.old"
  only:
    - master
  tags:
    - release-apache

Apache Development:
  stage: deploy-dev-apache
  script:
    - "[ -d /var/www/html/build-tmp.enpaul-dev ] && rm -r /var/www/html/build-tmp.enpaul-dev"
    - mkdir /var/www/html/build-tmp.enpaul-dev
    - cp -r ./* /var/www/html/build-tmp.enpaul-dev/
    - rm /var/www/html/build-tmp.enpaul-dev/web.config
    - "[ -d /var/www/html/enpaul-dev ] && mv /var/www/html/enpaul-dev /var/www/html/enpaul-dev.old"
    - mv /var/www/html/build-tmp.enpaul-dev /var/www/html/enpaul-dev
    - "[ -d /var/www/html/enpaul-dev.old ] && rm -r /var/www/html/enpaul-dev.old"
  only:
    - development
  tags:
    - dev-apache
